spring:
  profiles:
    active: local
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
  rabbitmq:
    host: ${vcap.services.p-rabbitmq.credentials.protocols.amqp.host:localhost}
    port: ${vcap.services.p-rabbitmq.credentials.protocols.amqp.port:5672}
    username: ${vcap.services.p-rabbitmq.credentials.protocols.amqp.username:guest}
    password: ${vcap.services.p-rabbitmq.credentials.protocols.amqp.password:guest}
    virtualHost: ${vcap.services.p-rabbitmq.credentials.protocols.amqp.vhost:/}
logging:
  level:
    io.pivotal.demo: DEBUG
    org.hibernate.SQL: DEBUG

---
spring:
  profiles: local
  datasource:
    platform: h2
  
---
spring:
  profiles: cloud
  datasource:
    platform: mysql  